exclude:
  - "app/assets/stylesheets/_settings.scss"
  - "app/assets/stylesheets/foundation_and_overrides.scss"

linters:
  Comment:
    enabled: false

  StringQuotes:
    enabled: true
    style: double_quotes

  SelectorFormat:
    enabled: false
