# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fa4ca11f0a63bff9ff2ca7ee9136de6d53e34066e50153b5579bd1549721489a848d4f46ea952421da09a3cf9e8f1494d6a8cb1344401e0a6f269de5a80c899

test:
  secret_key_base: fb13762d8d12e02327315aec965f2854049f4da5c78e83590fcabda0f4dbecae34bd80fae03f8f7daa0e8e9a8bcc3ce2e340e5dfae74b6c0909147322d2ef874

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
